- hosts: openstack
  gather_facts: no
  tasks:
    - name: Provision openstack instance
      os_server:
        name: "{{ server_name }}"
        network: "{{ server_network }}"
        flavor: "{{ server_flavor }}"
        image: "{{ server_image }}"
        key_name: "{{ server_key_name }}"
        floating_ips:
          - "{{ server_fip }}"
    
- hosts: harbor
  gather_facts: no
  tasks:
    - name: Wait 600 seconds for target connection to become reachable/usable
      wait_for_connection:

- hosts: harbor
  tasks:
    #- name: Setup Certbot
    #  import_role: name=brtknr.certbot
    - name: Install Harbor
      import_role: name=stackhpc.harbor
